### ISSUE TITLE
TMI : Todo Manage Interface

### ISSUE THREAD

**Issue by onnoo** [onnoo/TMI#30]
기존 소프트웨어 이름을 xnen에서 tmi로 바꾸었습니다.
이에 맞게 메인 페이지 디자인도 vim을 벤치마킹하여 디자인하였습니다.

구현해야할 사항들 :

- [x] todo table layout 및 커서 이동 구현
- [x] add 기능 구현
- [x] add -d 기능 구현
- [ ] mv 기능 구현
- [x] mod 기능 구현
- [ ] history 기능 구현
- [x] directory 에 따른 sql table 구현
- [x] check 기능 구현
- [x] task 자동완성 기능 구현
- [x] man-page 구현
